title = "Tinkerers - Torbay"
subtitle = "Create, Learn, Share"
baseURL = "https://tinkerers.uk"
languageCode = "en-gb"
theme = 'ananke'
resourceDir = "../resources"

DefaultContentLanguage = "en"
#SectionPagesMenu = "main" # If you uncomment this you will get automatic section entries in the main menu
paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-PW1WZH11RF"
enableRobotsTXT = true

[params]
  text_color = "mid-gray"
  date_format = ""
  author = ""
  #body_classes = "bg-near-white"
  favicon = "/img/logo_pink_sm.png"
  site_logo = "/img/logo_pink_sm.png"
  description = "Create, Learn, Share"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 10

[deployment]

[[deployment.targets]]
name = "www.tinkerers.uk"
URL = "s3://www.tinkerers.uk?region=eu-west-2"

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
# Cache images, but don't compress
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
# Compress text based assets
pattern = "^.+\\.(html|xml|json)$"
gzip = true