name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Deploy
    # Doesn't use latest Ubuntu as it breaks S3 sync command
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repos
        uses: actions/checkout@v4
        with:
          # Submodules added to allow build to access theme files
          submodules: 'recursive'
          fetch-depth: 0
      - name: Install Hugo
        run: sudo snap install hugo
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Hugo Build
        env:
          HUGO_ENVIRONMENT: 'production'  # Backward compatibility
          HUGO_ENV: 'production'
        run: hugo --logLevel info
      - name: Deploy site
        run: hugo deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}